version: '3.8'

services:
  movie_mysql:
    image: mysql:8.0
    container_name: movie_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - movie_mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  movie_redis:
    image: redis:7.0
    container_name: movie_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - movie_redis_data:/data

volumes:
  movie_mysql_data:
  movie_redis_data:

networks:
  default:
    name: movie_network